name = "Barcelona Gym"
type = "javascript"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "modules"
